config/routes.rb
Rails.application.routes.draw do
  constraints format: :json do
    resources :funnels, only: [:index]
    resources :validations, only: [] do
      collection do
        get :email
        get :phone
      end
    end
  end

  resources :apply, only: [:index, :create, :update] do
    collection do
      get :details
      get :quiz
      post :save_quiz, path: 'save-quiz'
      get :background_check, path: 'background-check'
      get :confirmation
      post :find_existing, path: 'find-existing-application'
    end
  end

  root to: 'home#index'
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  PHONE_TYPES = ['iPhone 6/6 Plus', 'iPhone 6s/6s Plus', 'iPhone 5/5S', 'iPhone 4/4S', 'iPhone 3G/3GS', 'Android 4.0+ (less than 2 years old)', 'Android 2.2/2.3 (over 2 years old)', 'Windows Phone', 'Blackberry', 'Other'].freeze
  REGIONS = ['San Francisco Bay Area', 'Chicago', 'Boston', 'NYC', 'Toronto', 'Berlin', 'Delhi'].freeze
  WORKFLOW_STATES = ['applied', 'quiz_started', 'quiz_completed', 'onboarding_requested', 'onboarding_completed', 'hired', 'rejected'].freeze

  after_initialize :set_initial_state

  scope :created_range, ->(start_date, end_date) { where("created_at >= ? AND created_at <= ?", start_date, end_date) }
  scope :by_created_at_week, -> { group("strftime('%Y-%m-%d', created_at)") }
  scope :by_workflow_state, -> { group(:workflow_state) }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true, unless: ->{ self.new_record? }
  validates :phone_type, presence: true, inclusion: { in: PHONE_TYPES }, unless: ->{ self.new_record? }
  validates :workflow_state, inclusion: { in: WORKFLOW_STATES }, presence: true
  validates :region, presence: true, inclusion: { in: REGIONS }, unless: ->{ self.new_record? }

  def request_onboarding
    if self.workflow_state == 'quiz_completed'
      self.workflow_state = 'onboarding_requested'
      self.save
    end
  end

  def application_stage
    return :details if self.workflow_state == 'applied'
    return :background_check if self.workflow_state == 'quiz_completed'
    return :confirmation if self.workflow_state == 'onboarding_requested'
  end

  private

  def set_initial_state
    if self.new_record?
      self.workflow_state = WORKFLOW_STATES[0]
    end
  end
end

app/models/funnel.rb
class Funnel

  def self.applicants_by_stage(start_date, end_date)
    funnel_stage_counts = Applicant.created_range(start_date, end_date)
                                   .by_created_at_week
                                   .by_workflow_state
                                   .count(:workflow_state)

    mapped_counts = funnel_stage_counts.inject(Hash.new{ |h, key| h[key] = {} }) do |hash,(keys, value)|
      parsed_date = Date.parse(keys.first)
      date_range_key = "#{parsed_date.beginning_of_week}-#{parsed_date.end_of_week}"
      hash[date_range_key][keys.last] = value
      hash
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apply_controller.rb
class ApplyController < ApplicationController
  before_action :find_applicant_from_session_or_redirect, only: [:update, :quiz, :background_check, :confirmation, :details]

  def index
    redirect_to root_url
  end

  def find_existing
    @applicant = Applicant.where(email: params[:email]).first
    if @applicant
      session[:applicant] = @applicant
      flash[:notice] = t('home.existing_application_modal.found_application', first_name: @applicant.first_name)
      redirect_to action: @applicant.application_stage
    else
      flash[:error] = t('home.existing_application_modal.no_such_email_error')
      redirect_to root_url
    end
  end

  def create
    @applicant = Applicant.new(applicant_params)
    if @applicant.save
      session[:applicant] = @applicant
      session[:application_step] = :details
      redirect_to details_apply_index_path
    else
      flash[:error] = @applicant.errors.full_messages if @applicant.errors.any?
      redirect_to root_url
    end
  end

  def update
    @applicant.assign_attributes(applicant_params)
    if @applicant.save
      session[:applicant] = @applicant
      session[:application_step] = :quiz
      redirect_to action: :quiz
    else
      flash[:error] = @applicant.errors.full_messages if @applicant.errors.any?
      redirect_to details_apply_index_path
    end
  end

  def save_quiz
    @applicant = Applicant.find(params[:id])
    if(params[:workflow_state] == 'quiz_started')
      @applicant.update_attributes(workflow_state: 'quiz_started')
      render json: true
    elsif(params[:workflow_state] == 'quiz_completed')
      @applicant.update_attributes(workflow_state: 'quiz_completed')
      render json: true
    else
      render json: ''
    end
  end

  def details
    @current_step = :details
  end

  def quiz
    @current_step = :quiz
  end

  def background_check
    @current_step = :background_check
  end

  def confirmation
    @current_step = :confirmation
    # change the applicants workflow_state from 'quiz_completed' to 'onboarding_requested'
    @applicant.request_onboarding
  end

  private

  def find_applicant_from_session_or_redirect
    if session[:applicant]
      @applicant = Applicant.find(session[:applicant]['id'])
    else
      redirect_to root_url
    end
  end

  def applicant_params
    params.require(:applicant).permit(:first_name, :last_name, :email, :phone, :phone_type, :region, :over_21)
  end
end

app/controllers/funnels_controller.rb
class FunnelsController < ApplicationController

  def index
    start_date = params.fetch(:start_date, 1.week.ago)
    end_date = params.fetch(:end_date, Time.zone.now)
    @funnels = Funnel.applicants_by_stage(start_date, end_date)
    render json: @funnels.to_json
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:applicant]
      @applicant = Applicant.find(session[:applicant]['id'])
      redirect_to controller: 'apply', action: @applicant.application_stage
    else
      @applicant = Applicant.new
    end
  end
end

app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def email
    email_exists = Applicant.where(email: params[:value]).exists?
    render json: !email_exists
  end

  def phone
    applicant = Applicant.find(params[:applicant_id])
    applicant.assign_attributes(phone: params[:value])
    applicant.valid?
    render json: applicant.errors[:phone].empty?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/apply/_application_steps.html.slim
.application-steps-wrapper.section-wrapper
  .application-steps-inner.section-inner
    ul.application-steps
      li.application-step
        = t('application_steps.get_started')
      li.application-step class=(('current-step' if @current_step == :details))
        = t('application_steps.details')
      li.application-step class=(('current-step' if @current_step == :quiz))
        = t('application_steps.quiz')
      li.application-step class=(('current-step' if @current_step == :background_check))
        = t('application_steps.background_check')
      li.application-step class=(('current-step' if @current_step == :confirmation))
        = t('application_steps.confirmation')

app/views/apply/background_check.html.slim
- title "Background Check"
= render 'apply/application_steps'
.background-check-wrapper.section-wrapper
  .background-check-inner.section-inner

    .page-header
      h1= t('apply.background_check.header')

    .legal-copy-wrapper
      = simple_format t('apply.background_check.release')

    .background-back-agree-wrapper
      = label_tag 'background_check_agree' do
        = check_box_tag 'background_check_agree'
        = t('apply.background_check.agree_text')

    .background-check-continue-button
      = link_to t('apply.background_check.continue_button'), confirmation_apply_index_path, class: 'button disabled'

app/views/apply/confirmation.html.slim
- title "Confirmation"
= render 'apply/application_steps'
.confirmation-wrapper.section-wrapper
  .confirmation-inner.section-inner

    .page-header
      h1= t('apply.confirmation.header')

    .page-content
      = t('apply.confirmation.status', state: @applicant.workflow_state)

app/views/apply/details.html.slim
- title "Your Details"
= render 'apply/application_steps'
.details-wrapper.section-wrapper
  .details-inner.section-inner
    .page-header
      h1= t('apply.details.header')
    .form-wrapper
      = form_for @applicant, url: { controller: :apply, action: 'update', id: @applicant }, method: :put do |f|
        ul.form-inputs
          li.input-group
            = f.label :over_21, t('apply.details.form.over_21')
            = f.check_box :over_21
          li.input-group
            i.fa.fa-warning

            = f.label :phone, t('apply.details.form.phone')
            = f.text_field :phone, placeholder: t('apply.details.form.phone')
          li.input-group
            i.fa.fa-warning
            = f.label :phone_type, t('apply.details.form.phone_type')
            = f.select :phone_type, Applicant::PHONE_TYPES, include_blank: true
          li.input-group
            i.fa.fa-warning
            = f.label :region, t('apply.details.form.region')
            = f.select :region, Applicant::REGIONS, include_blank: true

          li.input-group.input-submit
            = f.submit(t('apply.details.form.submit'), class: 'button')

javascript:
  window.applicant_id = "#{@applicant.id}"

app/views/apply/quiz.html.slim
- title "Shopper Quiz"
= render 'apply/application_steps'
.quiz-wrapper.section-wrapper
  .quiz-inner.section-inner

    .page-header
      h1= t('apply.quiz.header')
    .welcome-text
      p= t('apply.quiz.subhead')

    = react_component('QuizWidget', {}, { prerender: true })

javascript:
  window.updateApplicationStateUrl = "#{save_quiz_apply_index_path}"
  window.currentApplicationID = "#{@applicant.id}"
  window.continueApplicationLink = "#{background_check_apply_index_path}"

app/views/home/_existing_application_modal.html.slim
.existing-application-modal-overlay
.existing-application-modal
  .existing-application-inner
    h3= t('home.existing_application_modal.title')
    span= t('home.existing_application_modal.subhead')

    .close
      i.fa.fa-close

    = form_tag find_existing_apply_index_path, id: 'existing_application_form' do
      .input-wrapper
        i.fa.fa-warning
        = text_field_tag 'email', nil, type: :email, placeholder: t('home.existing_application_modal.email')
      = submit_tag t('home.existing_application_modal.submit'), class: 'button disabled'

app/views/home/_get_started.html.slim
.home-get-started-wrapper.section-wrapper
  .home-get-started-inner.section-inner
    h3= t('home.get_started.headline')
    h4= t('home.get_started.subhead')

    .get-started-cta
      .button= t('home.get_started.cta')

app/views/home/_header.html.slim
.home-headline-wrapper.section-wrapper
  .home-headline-inner.section-inner
    h1= t('home.hero.headline')
    h2= t('home.hero.subhead')

    .hero-form-wrapper
      h3= t('home.hero.cta')
      = render "home/start_signup_form"
      h6.existing-application= t('home.hero.existing_application')

app/views/home/_how_it_works.html.slim
.home-how-it-works-wrapper.section-wrapper
  .home-how-it-works-inner.section-inner
    h3.section-header= t('home.how_it_works.headline')
    h4.section-subhead= t('home.how_it_works.subhead')

    .flex-row-container.info-icons-group
      .flex-column.info-icon
        i.fa.fa-arrow-right
        h5= t('home.how_it_works.first_topic_heading')
        p= t('home.how_it_works.first_topic_body')
      .flex-column.info-icon
        i.fa.fa-cutlery
        h5= t('home.how_it_works.second_topic_heading')
        p= t('home.how_it_works.second_topic_body')
      .flex-column.info-icon
        i.fa.fa-money
        h5= t('home.how_it_works.third_topic_heading')
        p= t('home.how_it_works.third_topic_body')

app/views/home/_start_signup_form.html.slim
= form_for @applicant, url: { controller: :apply } do |f|
  ul.form-inputs
    li.input-group
      i.fa.fa-warning
      = f.label :first_name, t('home.application_start_form.first_name')
      = f.text_field :first_name, placeholder: t('home.application_start_form.first_name')

    li.input-group
      i.fa.fa-warning
      = f.label :last_name, t('home.application_start_form.last_name')
      = f.text_field :last_name, placeholder: t('home.application_start_form.last_name')

    li.input-group
      i.fa.fa-warning
      = f.label :email, t('home.application_start_form.email')
      = f.text_field :email, placeholder: t('home.application_start_form.email'), type: 'email'

    li.input-group.input-submit
      = f.submit(t('home.application_start_form.submit'), class: 'button')

app/views/home/_what_is_instacart.html.slim
.home-about-wrapper.section-wrapper
  .home-about-inner.section-inner
    h3.section-header= t('home.about.headline')
    h4.section-subhead= t('home.about.subhead')

    .flex-row-container.info-icons-group
      .flex-column.info-icon
        i.fa.fa-mobile
        h5= t('home.about.first_topic_heading')
        p= t('home.about.first_topic_body')
      .flex-column.info-icon
        i.fa.fa-shopping-cart
        h5= t('home.about.second_topic_heading')
        p= t('home.about.second_topic_body')
      .flex-column.info-icon
        i.fa.fa-globe
        h5= t('home.about.third_topic_heading')
        p= t('home.about.third_topic_body')

app/views/home/index.html.slim
= render "home/header"
= render "home/what_is_instacart"
= render "home/how_it_works"
= render "home/get_started"

= render 'home/existing_application_modal'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= content_for?(:title) ? "#{content_for(:title)} | Instacart Shoppers" : "Instacart Shoppers" %>
  </title>

  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700', media: 'all' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>

  <%= link_to root_path, { class: 'logo' } do %>
    <h1 >
      <%= image_tag('instacart-logo.png') %>
    </h1>
  <% end %>


</header>

<%= render('shared/flash_notices') %>
<div class='content-wrapper'>
  <div class='content-wrapper-inner'>
    <%= yield %>
  </div>
</div>

<%= render('shared/footer') %>

</body>
</html>

app/views/shared/_flash_notices.html.slim
- unless flash.empty?
  .flash-messages-wrapper
    .flash-messages-inner
      - flash.each do |f|
        - if f[1].is_a?(Array)
          - f[1].each do |message|
            .message-wrapper class=(f[0])
              .message-inner
                - if f[0] == 'error'
                  i.fa.fa-warning
                - else
                  i.fa.fa-bullhorn
                span= message
        - else
          .message-wrapper class=(f[0])
            .message-inner
              - if f[0] == 'error'
                i.fa.fa-warning
              - else
                i.fa.fa-bullhorn
              span= f[1]

app/views/shared/_footer.html.slim
footer.footer-wrapper
  .footer-inner
    = "© Instacart #{Time.now.strftime('%Y')}"